//validation for all inputs
let form = document.getElementById("form");
let inputToday = document.getElementById("name");
let inputGender = document.getElementById("gender");
let inputDate = document.getElementById("birth");
let week = document.getElementById("week");
//validation for all errors
let today_error = document.getElementById("name_error");
let gender_error = document.getElementById("gender_error");
let date_error = document.getElementById("date_error");
//validation of button submit
